version: '2'

services:
  reverse-proxy:
    container_name: nginx-routing
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.nginx-routing
    ports:
      - "8080:80"
      - "443:443"

  novels-api:
    container_name: novels-api
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.novels-api
    env_file: ./config/mysql/.env
    volumes:
      #only dev
      - ./app/api/novels:/go/src/app
    command: go-wrapper run

  sentences-api:
    container_name: sentences-api
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.sentences-api
    env_file: ./config/mysql/.env
    volumes:
      #only dev
      - ./app/api/novels/sentences:/go/src/app
    command: go-wrapper run

  sql-proxy:
    container_name: mysql-proxy
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.sql-proxy
    volumes:
      - /cloudsql:/cloudsql
