version: '2'

services:
  mysql-golang:
    container_name: relay-novel-mysql
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile-mysql
    volumes:
      - ./config/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=bookshelf
      - MYSQL_USER=editor
      - MYSQL_PASSWORD=edit
      - MYSQL_ROOT_PASSWORD=osechiman

  golang:
    container_name: relay-novel-golang
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile-golang
    depends_on:
      - mysql-golang
    links:
      - mysql-golang:mysql

  nginx-golang:
    container_name: relay-novel-nginx
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile-nginx
    ports:
      - "8080:80"
    depends_on:
      - golang
    links:
      - golang:golang
