version: '2'

services:
  reverse-proxy:
    container_name: relay-novel-nginx-routing
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.nginx-routing
    ports:
      - "8080:80"
      - "443:443"

  novels-api:
    container_name: relay-novel-novels-api
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.novels-api
    env_file: ./config/mysql/.env

  sql-proxy:
    container_name: relay-novel-mysql-proxy
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.sql-proxy
    volumes:
      - /cloudsql:/cloudsql
