apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
      kubernetes.io/ingress.global-static-ip-name: "ingress-ip"
spec:
  backend:
    serviceName: nginx-routing
    servicePort: 80
