apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentences-api
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: golang
    name: sentences-api
    role: api
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   matchLabels:
  #     app: guestbook
  #     role: master
  #     tier: backend
  template:
    metadata:
      labels:
        app: golang
        name: sentences-api
        role: api
    spec:
      containers:
      - name: sentences-api
        image: asia.gcr.io/relaynovel-173804/sentences-api:3bf27e67620910780f00215a8ac853cc70de67ce
        resources:
          requests:
            cpu: 100m
            memory: 10Mi
