apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: novels-api
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: golang
    name: novels-api
    role: api
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 2
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   matchLabels:
  #     app: guestbook
  #     role: master
  #     tier: backend
  template:
    metadata:
      labels:
        app: golang
        name: novels-api
        role: api
    spec:
      containers:
      - name: novels-api
        image: asia.gcr.io/relaynovel-173804/novels-api:276f1daf2c4b8ef0d1f8c86b633626bbfcdd1ea8
        env:
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: Ngj9GbsC9yBHKHOI
        - name: DB_HOST
          value: mysql-proxy.default.svc.cluster.local
        - name: DATABASE
          value: RelayNovel
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
