apiVersion: version:1
kind: Service
metadata:
  name: nginx-routing
  labels:
    app: nginx
    name: nginx-routing
    role: reverse-proxy
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  - port: 443
    targetPort: 443
  selector:
    app: nginx
    name: nginx-routing
    role: reverse-proxy
