FROM gcr.io/cloudsql-docker/gce-proxy:1.09
LABEL maintainer "osechiman@gmail.com"

VOLUME ["/cloudsql"]
ENTRYPOINT ["/cloud_sql_proxy"]
CMD ["-instances=relaynovel-173804:asia-east1:relay-novels=tcp:0.0.0.0:3306"]
