# golang on alpine
FROM golang:1.8-alpine

# producer
MAINTAINER osechiman
# <osechiman@gmail.com>

# package update
RUN apk update

# timezone asai/Tokyo
RUN apk add tzdata && cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && apk del tzdata

# language setting
RUN echo "export LC_ALL=jp_JP.UTF-8 >> /etc/profile && \
    echo "export LANGUAGE=jp_JP.UTF-8 >> /etc/profile

# install package
RUN apk add --virtual=relay-novel \
    make \
    gcc \
    curl \
    git \
    jq \
    vim \
    mercurial

# dein.vim install
RUN curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > /tmp/installer.sh

# dein.vim install
RUN sh /tmp/installer.sh /etc/vim/.vim && \
    rm /tmp/installer.sh

# setting files
COPY ./config/vim/vimrc /etc/vim/vimrc
COPY ./config/vim/config /etc/vim/.vim/config

# go file
COPY ./src/index.go /go

# entrypoint
ENTRYPOINT ["go", "run", "/go/index.go"]
