FROM nginx:1.13.3-alpine
LABEL maintainer "osechiman@gmail.com"

COPY ./config/nginx/api-reverse-proxy.conf /etc/nginx/conf.d/default.conf

# package update
RUN apk update

# timezone asai/Tokyo
RUN apk add tzdata && cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && apk del tzdata

# language setting
RUN echo "export LC_ALL=jp_JP.UTF-8 >> /etc/profile && \
    echo "export LANGUAGE=jp_JP.UTF-8 >> /etc/profile

