# mongodn on debian
FROM mongo:3.4.1

# producer
MAINTAINER osechiman
# <osechiman@gmail.com>

# package update
RUN apt-get update

# timezone asai/Tokyo
RUN echo "Asia/Tokyo" > /etc/timezone && \
    dpkg-reconfigure -f noninteractive tzdata

# language setting
RUN echo "export LC_ALL=jp_JP.UTF-8 >> /etc/profile && \
    echo "export LANGUAGE=jp_JP.UTF-8 >> /etc/profile
