apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: status-api
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: golang
    name: status-api
    role: api
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   matchLabels:
  #     app: guestbook
  #     role: master
  #     tier: backend
  template:
    metadata:
      labels:
        app: golang
        name: status-api
        role: api
    spec:
      containers:
      - name: status-api
        image: asia.gcr.io/relaynovel-173804/status-api:fb9c187a6fbad2402d6dc177e6fd8d1ccfe2b894
        resources:
          requests:
            cpu: 100m
            memory: 10Mi
