apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-proxy
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: mysql
    name: mysql-proxy
    role: sql-proxy
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   matchLabels:
  #     app: guestbook
  #     role: master
  #     tier: backend
  template:
    metadata:
      labels:
        app: mysql
        name: mysql-proxy
        role: sql-proxy
    spec:
      containers:
      - name: mysql-proxy
        image: asia.gcr.io/relaynovel-173804/sql-proxy:COMMIT_HASH
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
