apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-routing
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: nginx
    name: nginx-routing
    role: reverse-proxy
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   matchLabels:
  #     app: guestbook
  #     role: master
  #     tier: backend
  template:
    metadata:
      labels:
        app: nginx
        name: nginx-routing
        role: reverse-proxy
    spec:
      containers:
      - name: nginx-routing
        image: asia.gcr.io/relaynovel-173804/reverse-proxy:fb9c187a6fbad2402d6dc177e6fd8d1ccfe2b894
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
