apiVersion: v1
kind: Service
metadata:
  name: nginx-routing
  labels:
    app: nginx
    name: nginx-routing
    role: reverse-proxy
spec:
  ports:
    # the port that this service should serve on
  - protocol: TCP
    name: tcp-80
    port: 80
    targetPort: 80
  selector:
    name: nginx-routing
