apiVersion: v1
kind: Service
metadata:
  name: nginx-routing
  labels:
    app: nginx
    name: nginx-routing
    role: reverse-proxy
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - name: nginx-http
      port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    name: nginx-routing
